In [15]:
import pandas as pd
import numpy as np

In [16]:
df = pd.read_json('https://www.dropbox.com/s/5iw2kgh45g4p1mk/joinCluster.json?dl=1')

In [17]:
df.head(3)

,RowID,Fecha,IDItem,NumeroUbicacion,Dewey,Ubicacion,Llave,Programa,Facultad,IDUsuario,...,Autor,Titulo,AnioPublicacion,DeweyEspecifico,TemaDewey,Temas,Union,Peso_x,Peso_y,cluster
0,Row0,1547050497000,80000005327627,720.98 A71S,720,COL-GRAL-2,866245,CARRERA DE ARQUITECTURA,arquitectura y diseño,c361c772cd0220bb16dcfb2ad803e4903334ab94,...,"Arango Cardinal, Silvia 1948-",Ciudad y arquitectura seis generaciones que co...,2012.0,720.98,Arquitectura latinoamericana,"[arquitectur, histori, amer, latin]",arquitectur histori amer latin,0.25,5.25,16
1,Row1,1547050500000,80000001191496,720.9861 A71,720,COL-GRAL-2,309945,CARRERA DE ARQUITECTURA,arquitectura y diseño,c361c772cd0220bb16dcfb2ad803e4903334ab94,...,"Arango Cardinal, Silvia 1948-",Historia de la arquitectura en Colombia Silvia...,1993.0,720.9861,Arquitectura colombiana,"[arquitectur, colonial, histori, colombi]",arquitectur colonial histori colombi,0.25,5.25,16
2,Row2,1547138763000,80000004979759,540 CH15Q 2010,540,COL-GRAL-3,822727,CARRERA DE ARQUITECTURA,arquitectura y diseño,87b0e5a61ed712ddfaf5d478ad68c87c825997e9,...,"Chang, Raymond",Química Raymond Chang ; revisión técnica Rosa ...,2010.0,540,Química,[quimic],quimic,0.25,5.50,1

Se creará un DataFrame el cual tendrá como columnas: IDUsuario, Fecha, Llave, Calificacion. Cada fila del dataframe representa una retroalimentación por parte del usuario cuando se realiza una recomendación. El usuario unicamente puede dicidir si le gustó o no la recomendación a través de botones de like y dislike por lo cual el atributo calificación solo tendrá dos valores. Si a el usuario le agrada la recomendación se da un valor de 1 si no -1. Esto con el fin de modificar los pesos que tienen los usuarios por dewey cuando se generan los clusters y en caso de que las recomendaciones no sean adecuadas cambiar al usuario de cluster.

In [52]:
calificaciones = pd.DataFrame(columns= ["IDUsuario", "Fecha", "Llave", "Calificación"])
calificaciones

Empty DataFrame
Columns: [IDUsuario, Fecha, Llave, Calificación]
Index: []

In [53]:
from faker import Faker
fake = Faker()
Faker.seed(0)
for _ in range(5):
    print(fake.pybool())

True
True
False
True
True

In [54]:
import random
for i in range(100):
    id = random.choice(df.IDUsuario.unique())
    llave = random.choice(df.Llave.unique())
    cal = random.choice([-1,1])
    anio = random.choice([2021])
    calificaciones.loc[i] = [id,anio,llave,cal]

In [55]:
calificaciones

                                   IDUsuario Fecha   Llave Calificación
0   20305795a9d479593939228fd77775979dee7ab9  2021  716532            1
1   9133a6859dd89c356928523f031999d6d078084e  2021  257389            1
2   c597c2028748ffc15c71803f793e5b32de6fae53  2021  871239           -1
3   38084ad3413e81664f23b32805236b847fdb833f  2021  311749           -1
4   7af6d9b095d5d7b7a39be213d5aead2274845c11  2021  885136           -1
..                                       ...   ...     ...          ...
95  1dad1568cfb605c32704f85084e3adde3a1e5ea6  2021  855275            1
96  65448be15ec8f4708c04b12855e7a3d6bac211ee  2021  672239            1
97  3c32eb49f865ad9d1bfdabe218d6577939afbd76  2021  886411           -1
98  869cb2f894c91d38fdbb311fa15917c9dd95b841  2021  541637           -1
99  25207087aed601413d9fa05330a93bf47259a866  2021  351608            1

[100 rows x 4 columns]