# Cargar datos

In [1]:
# from google.colab import drive
# drive.mount('/content/drive')

In [2]:
import pandas as pd
import numpy as np

In [4]:
# Archivo de prestamos
df_prestamos = pd.read_json('../data/TABLA_JOIN.json')

In [5]:
display(df_prestamos)

,RowID,Mes,Fecha,IDItem,NumeroUbicacion,Dewey,Ubicacion,TipoItem_x,Llave_x,Perfil,...,Copias,Autor,Titulo,Tema650,AnioPublicación,NO_DEWEY,ENCABEZAMIENTO,original,Temas,union
0,Row0,Enero,1546992000000,80000005327627,720.98 A71S,720,COL-GRAL-2,LIBRO,866245,A-EGRESADO,...,1,"Arango Cardinal, Silvia 1948-",Ciudad y arquitectura seis generaciones que co...,arquitectura historia america latina,2012.0,720.98,Arquitectura latinoamericana,arquitectura historia america latina,"[arquitectur, histori, amer, latin]",arquitectur histori amer latin
1,Row1,Enero,1546992000000,80000001191496,720.9861 A71,720,COL-GRAL-2,LIBRO,309945,A-EGRESADO,...,2,"Arango Cardinal, Silvia 1948-",Historia de la arquitectura en Colombia Silvia...,arquitectura colonial historia colombia,1993.0,720.9861,Arquitectura colombiana,arquitectura colonial historia colombia,"[arquitectur, colonial, histori, colombi]",arquitectur colonial histori colombi
2,Row2,Enero,1547078400000,80000004979759,540 CH15Q 2010,540,COL-GRAL-3,LIBRO,822727,A-EGRESADO,...,2,"Chang, Raymond",Química Raymond Chang ; revisión técnica Rosa ...,quimica,2010.0,540,Química,quimica,[quimic],quimic
3,Row3,Enero,1547078400000,80000004509512,512 B151,510,COL-GRAL-3,LIBRO,784541,A-EGRESADO,...,1,"Baldor, J. Aurelio",Álgebra con gráficos y 6523 ejercicios y probl...,algebra,2009.0,512,Álgebra,algebra,[algebr],algebr
4,Row4,Enero,1547251200000,80000005270756,712 M17E,710,COL-GRAL-2,LIBRO,858473,A-EGRESADO,...,2,"Martínez de Pisón, Eduardo 1937-",Miradas sobre el paisaje Eduardo Martínez de P...,arquitectura del paisaje,2009.0,712,Arquitectura del paisaje,arquitectura del paisaje,"[arquitectur, paisaj]",arquitectur paisaj
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517081,Row543896,Diciembre,1546214400000,80000005573398,370.1 E47E,370,COL-GRAL-3,LIBRO,914491,A-EGRESADO,...,1,"Eisner, Elliot W.",La escuela que necesitamos ensayos personales ...,filosofia de la educacion,2002.0,370.1,Filosofía de la educación,filosofia de la educacion,"[filosofi, educacion]",filosofi educacion
517082,Row543897,Diciembre,1546214400000,60000000046504,370.1 CH65,370,COL-GRAL-3,LIBRO,747839,A-EGRESADO,...,2,"Chomsky, Noam 1928-",La (des) educación Noam Chomsky ; edición e in...,filosofia de la educacion,2007.0,370.1,Filosofía de la educación,filosofia de la educacion,"[filosofi, educacion]",filosofi educacion
517083,Row543898,Diciembre,1546214400000,80000002767872,809 H182 V.1,800,COL-GRAL-0,LIBRO,522997,A-EGRESADO,...,2,"Hauser, Arnold 1892-1978",Historia social de la literatura y el arte Arn...,arte historia,1998.0,809,Literatura europea|xHistoria y crítica,arte historia,"[arte, histori]",arte histori
517084,Row543899,Diciembre,1546214400000,80000004114631,658.0076 G51,650,COL-GRAL-2,LIBRO,743895,A-EGRESADO,...,1,None,GMAT premier program the staff of kaplan test ...,examen de admision para graduados en administr...,2007.0,658.0076,Examen de admisión para graduados en administr...,examen de admision para graduados en administr...,"[exam, admision, gradu, administracion, empres]",exam admision gradu administracion empres
517085,Row543900,Diciembre,1546214400000,80000005104167,833 Z83SN,830,COL-GRAL-0,LITERATURA,841120,EG,...,1,"Zweig, Stefan 1881-1942",Noche fantástica Stefan Zweig ; traducción de ...,cuentos austriacos,2009.0,833,Novela suiza (Alemán),cuentos austriacos,"[cuent, austriac]",cuent austriac

In [6]:
df_prestamos.columns

Index(['RowID', 'Mes', 'Fecha', 'IDItem', 'NumeroUbicacion', 'Dewey',
       'Ubicacion', 'TipoItem_x', 'Llave_x', 'Perfil', 'Programa', 'Facultad',
       'IDUsario', 'Year', 'Signatura', 'UbicacionActual', 'TipoItem_y',
       'TotalPrestamos', 'Llave_y', 'Copias', 'Autor', 'Titulo', 'Tema650',
       'AnioPublicación', 'NO_DEWEY', 'ENCABEZAMIENTO', 'original', 'Temas',
       'union'],
      dtype='object')

In [7]:
# Archivo donde se calcularon los pesos para cada prestamo
df_pesos = pd.read_json('../data/data_to_build.json')
df_pesos

,Dewey,Llave_x,IDUsario,Peso del prestamos
1809,0,836405,0f655061dc0b588e221cd03bd3e7dfa056518ec3,13.000
2040,0,864918,95ae56fe5202b6a674123079b854aedee57f33d8,9.000
2747,0,918693,fed86974c1b264f8d7b6e36200c7ad5ca8ef5a90,6.250
2733,0,918693,0c6753cb0638b5141332010b8e670fbf7c82074b,6.000
422,0,355238,53f6e0708e3ac4f0687c78f76906f682242e1687,5.000
...,...,...,...,...
242993,Video,910655,6345baa824b642a2e5c752adaec9ff00786a7f75,0.125
241607,Video,752654,822efdea0e535fb37ccef60dc9e9ad82e8ee7e1c,0.125
242991,Video,910655,51fb8bc6df2f4f80beeafdfaf8bf0d2f8a05342e,0.125
242990,Video,910655,395733bdb8272fe03098bd8a9a28b9d2a08f32d1,0.125
241980,Video,811039,f879fffd9b5d10abccf60536ee4a37df62fda8a1,0.125

In [7]:
df_pesos.rename(columns={'Llave_x':'Llaves', 'IDUsario':'ID de usuario ok'}, inplace=True)

In [8]:
df_pesos.head()

,Dewey,Llaves,ID de usuario ok,Peso del prestamos
1809,0,836405,0f655061dc0b588e221cd03bd3e7dfa056518ec3,13.00
2040,0,864918,95ae56fe5202b6a674123079b854aedee57f33d8,9.00
2747,0,918693,fed86974c1b264f8d7b6e36200c7ad5ca8ef5a90,6.25
2733,0,918693,0c6753cb0638b5141332010b8e670fbf7c82074b,6.00
422,0,355238,53f6e0708e3ac4f0687c78f76906f682242e1687,5.00

In [60]:
import gzip, pickle, pickletools
filepath = "Cluster_temas.pkl"
with gzip.open(filepath, 'rb') as f:
    p = pickle.Unpickler(f)
    df_clusters = p.load()

In [61]:
# Archivo donde se calcularon los pesos para cada prestamo
df_clusters.head()

,aac,aafric,aalgebr,aandin,aar,abandon,abastec,abdom,abej,abelian,...,zon,zoolog,zoologi,zoonosis,zootecni,zorr,zost,zuli,cluster,id usuario
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,78,00063d52cf68c65d2a569e95c40345c4a305ccc7
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,9,0006b3bdabeaa5389b211c8487bd67d339c97ef7
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,32,000a0630c32a437052696f6921e3181f155291d0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,9,000c040064aedd76057c5309064a3823db970644
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,37,000f23e62e6d4995ede7090c6447ad6736edc4de

In [53]:
len(df_pesos['ID de usuario ok'].unique())

25235

In [75]:
df_clusters.loc[df_clusters['id usuario'] == '000a0630c32a437052696f6921e3181f155291d0']['cluster'].values[0]

32

In [77]:
df_p = df_pesos.copy()

In [82]:
df_p.drop(df_p[df_p['ID de usuario ok'] == '000a0630c32a437052696f6921e3181f155291d0'].index, inplace=True)

In [83]:
df_p.loc[df_p['ID de usuario ok'] == '000a0630c32a437052696f6921e3181f155291d0']

Empty DataFrame
Columns: [Dewey, Llaves, ID de usuario ok, Peso del prestamos]
Index: []

In [84]:
# df_pivot = df_pesos.copy()
# clusters = []
# for idU in df_pivot['ID de usuario ok']:
#     if(len(df_clusters.loc[df_clusters['id usuario'] == idU]) == 0):
#         df_pivot.drop(df_pivot[df_pivot['ID de usuario ok'] == idU].index, inplace=True)
#     else:
#         cluster = df_clusters.loc[df_clusters['id usuario'] == idU]['cluster'].values[0]
#         clusters.append(cluster)

# df_pivot['cluster'] = clusters

In [85]:
# df_pivot

,Dewey,Llaves,ID de usuario ok,Peso del prestamos,cluster
1809,0,836405,0f655061dc0b588e221cd03bd3e7dfa056518ec3,13.000,24
2040,0,864918,95ae56fe5202b6a674123079b854aedee57f33d8,9.000,9
2747,0,918693,fed86974c1b264f8d7b6e36200c7ad5ca8ef5a90,6.250,0
2733,0,918693,0c6753cb0638b5141332010b8e670fbf7c82074b,6.000,9
422,0,355238,53f6e0708e3ac4f0687c78f76906f682242e1687,5.000,148
...,...,...,...,...,...
242993,Video,910655,6345baa824b642a2e5c752adaec9ff00786a7f75,0.125,53
241607,Video,752654,822efdea0e535fb37ccef60dc9e9ad82e8ee7e1c,0.125,19
242991,Video,910655,51fb8bc6df2f4f80beeafdfaf8bf0d2f8a05342e,0.125,141
242990,Video,910655,395733bdb8272fe03098bd8a9a28b9d2a08f32d1,0.125,111
241980,Video,811039,f879fffd9b5d10abccf60536ee4a37df62fda8a1,0.125,67

In [86]:
# df_pivot.to_json('./pesos_con_cluster_no_promedio.json')

In [87]:
# Archivo donde se encuentran prestamos con su cluster asociado, sin promediar
df_pesos_clusters = pd.read_json('./pesos_con_cluster_no_promedio.json')

In [107]:
df_pesos_clusters

,Dewey,Llaves,ID de usuario ok,Peso del prestamos,cluster
1809,0,836405,0f655061dc0b588e221cd03bd3e7dfa056518ec3,13.000,24
2040,0,864918,95ae56fe5202b6a674123079b854aedee57f33d8,9.000,9
2747,0,918693,fed86974c1b264f8d7b6e36200c7ad5ca8ef5a90,6.250,0
2733,0,918693,0c6753cb0638b5141332010b8e670fbf7c82074b,6.000,9
422,0,355238,53f6e0708e3ac4f0687c78f76906f682242e1687,5.000,148
...,...,...,...,...,...
242993,Video,910655,6345baa824b642a2e5c752adaec9ff00786a7f75,0.125,53
241607,Video,752654,822efdea0e535fb37ccef60dc9e9ad82e8ee7e1c,0.125,19
242991,Video,910655,51fb8bc6df2f4f80beeafdfaf8bf0d2f8a05342e,0.125,141
242990,Video,910655,395733bdb8272fe03098bd8a9a28b9d2a08f32d1,0.125,111
241980,Video,811039,f879fffd9b5d10abccf60536ee4a37df62fda8a1,0.125,67

In [100]:
# df_pivot_time = df_pesos_clusters.copy()
# timestamps = []

# for i in range(0, len(df_pivot_time)):
# # for i in range(0, 200):
#     if(i % 200 == 0):
#         print(i, "de ", len(df_pivot_time))
#     idU = df_pivot_time.iloc[i]['ID de usuario ok']
#     llave = df_pivot_time.iloc[i]['Llaves']
#     piv = df_prestamos.loc[df_prestamos['IDUsario'] == idU]
#     piv_llave = df_prestamos.loc[df_prestamos['Llave_x'] == llave]['Fecha']
#     time = piv_llave.values[0]
#     timestamps.append(time)

0 de  244228
200 de  244228
400 de  244228
600 de  244228
800 de  244228
1000 de  244228
1200 de  244228
1400 de  244228
1600 de  244228
1800 de  244228
2000 de  244228
2200 de  244228
2400 de  244228
2600 de  244228
2800 de  244228
3000 de  244228
3200 de  244228
3400 de  244228
3600 de  244228
3800 de  244228
4000 de  244228
4200 de  244228
4400 de  244228
4600 de  244228
4800 de  244228
5000 de  244228
5200 de  244228
5400 de  244228
5600 de  244228
5800 de  244228
6000 de  244228
6200 de  244228
6400 de  244228
6600 de  244228
6800 de  244228
7000 de  244228
7200 de  244228
7400 de  244228
7600 de  244228
7800 de  244228
8000 de  244228
8200 de  244228
8400 de  244228
8600 de  244228
8800 de  244228
9000 de  244228
9200 de  244228
9400 de  244228
9600 de  244228
9800 de  244228
10000 de  244228
10200 de  244228
10400 de  244228
10600 de  244228
10800 de  244228
11000 de  244228
11200 de  244228
11400 de  244228
11600 de  244228
11800 de  244228
12000 de  244228
12200 de  244228
12400 de  244228
12600 de  244228
12800 de  244228
13000 de  244228
13200 de  244228
13400 de  244228
13600 de  244228
13800 de  244228
14000 de  244228
14200 de  244228
14400 de  244228
14600 de  244228
14800 de  244228
15000 de  244228
15200 de  244228
15400 de  244228
15600 de  244228
15800 de  244228
16000 de  244228
16200 de  244228
16400 de  244228
16600 de  244228
16800 de  244228
17000 de  244228
17200 de  244228
17400 de  244228
17600 de  244228
17800 de  244228
18000 de  244228
18200 de  244228
18400 de  244228
18600 de  244228
18800 de  244228
19000 de  244228
19200 de  244228
19400 de  244228
19600 de  244228
19800 de  244228
20000 de  244228
20200 de  244228
20400 de  244228
20600 de  244228
20800 de  244228
21000 de  244228
21200 de  244228
21400 de  244228
21600 de  244228
21800 de  244228
22000 de  244228
22200 de  244228
22400 de  244228
22600 de  244228
22800 de  244228
23000 de  244228
23200 de  244228
23400 de  244228
23600 de  244228
23800 de  244228
24000 de  244228
24200 de  244228
24400 de  244228
24600 de  244228
24800 de  244228
25000 de  244228
25200 de  244228
25400 de  244228
25600 de  244228
25800 de  244228
26000 de  244228
26200 de  244228
26400 de  244228
26600 de  244228
26800 de  244228
27000 de  244228
27200 de  244228
27400 de  244228
27600 de  244228
27800 de  244228
28000 de  244228
28200 de  244228
28400 de  244228
28600 de  244228
28800 de  244228
29000 de  244228
29200 de  244228
29400 de  244228
29600 de  244228
29800 de  244228
30000 de  244228
30200 de  244228
30400 de  244228
30600 de  244228
30800 de  244228
31000 de  244228
31200 de  244228
31400 de  244228
31600 de  244228
31800 de  244228
32000 de  244228
32200 de  244228
32400 de  244228
32600 de  244228
32800 de  244228
33000 de  244228
33200 de  244228
33400 de  244228
33600 de  244228
33800 de  244228
34000 de  244228
34200 de  244228
34400 de  244228
34600 de  244228
34800 de  244228
35000 de  244228
35200 de  244228
35400 de  244228
35600 de  244228
35800 de  244228
36000 de  244228
36200 de  244228
36400 de  244228
36600 de  244228
36800 de  244228
37000 de  244228
37200 de  244228
37400 de  244228
37600 de  244228
37800 de  244228
38000 de  244228
38200 de  244228
38400 de  244228
38600 de  244228
38800 de  244228
39000 de  244228
39200 de  244228
39400 de  244228
39600 de  244228
39800 de  244228
40000 de  244228
40200 de  244228
40400 de  244228
40600 de  244228
40800 de  244228
41000 de  244228
41200 de  244228
41400 de  244228
41600 de  244228
41800 de  244228
42000 de  244228
42200 de  244228
42400 de  244228
42600 de  244228
42800 de  244228
43000 de  244228
43200 de  244228
43400 de  244228
43600 de  244228
43800 de  244228
44000 de  244228
44200 de  244228
44400 de  244228
44600 de  244228
44800 de  244228
45000 de  244228
45200 de  244228
45400 de  244228
45600 de  244228
45800 de  244228
46000 de  244228
46200 de  244228
46400 de  244228
46600 de  244228
46800 de  244228
47000 de  244228
47200 de  244228
47400 de  244228
47600 de  244228
47800 de  244228
48000 de  244228
48200 de  244228
48400 de  244228
48600 de  244228
48800 de  244228
49000 de  244228
49200 de  244228
49400 de  244228
49600 de  244228
49800 de  244228
50000 de  244228
50200 de  244228
50400 de  244228
50600 de  244228
50800 de  244228
51000 de  244228
51200 de  244228
51400 de  244228
51600 de  244228
51800 de  244228
52000 de  244228
52200 de  244228
52400 de  244228
52600 de  244228
52800 de  244228
53000 de  244228
53200 de  244228
53400 de  244228
53600 de  244228
53800 de  244228
54000 de  244228
54200 de  244228
54400 de  244228
54600 de  244228
54800 de  244228
55000 de  244228
55200 de  244228
55400 de  244228
55600 de  244228
55800 de  244228
56000 de  244228
56200 de  244228
56400 de  244228
56600 de  244228
56800 de  244228
57000 de  244228
57200 de  244228
57400 de  244228
57600 de  244228
57800 de  244228
58000 de  244228
58200 de  244228
58400 de  244228
58600 de  244228
58800 de  244228
59000 de  244228
59200 de  244228
59400 de  244228
59600 de  244228
59800 de  244228
60000 de  244228
60200 de  244228
60400 de  244228
60600 de  244228
60800 de  244228
61000 de  244228
61200 de  244228
61400 de  244228
61600 de  244228
61800 de  244228
62000 de  244228
62200 de  244228
62400 de  244228
62600 de  244228
62800 de  244228
63000 de  244228
63200 de  244228
63400 de  244228
63600 de  244228
63800 de  244228
64000 de  244228
64200 de  244228
64400 de  244228
64600 de  244228
64800 de  244228
65000 de  244228
65200 de  244228
65400 de  244228
65600 de  244228
65800 de  244228
66000 de  244228
66200 de  244228
66400 de  244228
66600 de  244228
66800 de  244228
67000 de  244228
67200 de  244228
67400 de  244228
67600 de  244228
67800 de  244228
68000 de  244228
68200 de  244228
68400 de  244228
68600 de  244228
68800 de  244228
69000 de  244228
69200 de  244228
69400 de  244228
69600 de  244228
69800 de  244228
70000 de  244228
70200 de  244228
70400 de  244228
70600 de  244228
70800 de  244228
71000 de  244228
71200 de  244228
71400 de  244228
71600 de  244228
71800 de  244228
72000 de  244228
72200 de  244228
72400 de  244228
72600 de  244228
72800 de  244228
73000 de  244228
73200 de  244228
73400 de  244228
73600 de  244228
73800 de  244228
74000 de  244228
74200 de  244228
74400 de  244228
74600 de  244228
74800 de  244228
75000 de  244228
75200 de  244228
75400 de  244228
75600 de  244228
75800 de  244228
76000 de  244228
76200 de  244228
76400 de  244228
76600 de  244228
76800 de  244228
77000 de  244228
77200 de  244228
77400 de  244228
77600 de  244228
77800 de  244228
78000 de  244228
78200 de  244228
78400 de  244228
78600 de  244228
78800 de  244228
79000 de  244228
79200 de  244228
79400 de  244228
79600 de  244228
79800 de  244228
80000 de  244228
80200 de  244228
80400 de  244228
80600 de  244228
80800 de  244228
81000 de  244228
81200 de  244228
81400 de  244228
81600 de  244228
81800 de  244228
82000 de  244228
82200 de  244228
82400 de  244228
82600 de  244228
82800 de  244228
83000 de  244228
83200 de  244228
83400 de  244228
83600 de  244228
83800 de  244228
84000 de  244228
84200 de  244228
84400 de  244228
84600 de  244228
84800 de  244228
85000 de  244228
85200 de  244228
85400 de  244228
85600 de  244228
85800 de  244228
86000 de  244228
86200 de  244228
86400 de  244228
86600 de  244228
86800 de  244228
87000 de  244228
87200 de  244228
87400 de  244228
87600 de  244228
87800 de  244228
88000 de  244228
88200 de  244228
88400 de  244228
88600 de  244228
88800 de  244228
89000 de  244228
89200 de  244228
89400 de  244228
89600 de  244228
89800 de  244228
90000 de  244228
90200 de  244228
90400 de  244228
90600 de  244228
90800 de  244228
91000 de  244228
91200 de  244228
91400 de  244228
91600 de  244228
91800 de  244228
92000 de  244228
92200 de  244228
92400 de  244228
92600 de  244228
92800 de  244228
93000 de  244228
93200 de  244228
93400 de  244228
93600 de  244228
93800 de  244228
94000 de  244228
94200 de  244228
94400 de  244228
94600 de  244228
94800 de  244228
95000 de  244228
95200 de  244228
95400 de  244228
95600 de  244228
95800 de  244228
96000 de  244228
96200 de  244228
96400 de  244228
96600 de  244228
96800 de  244228
97000 de  244228

97200 de  244228
97400 de  244228
97600 de  244228
97800 de  244228
98000 de  244228
98200 de  244228
98400 de  244228
98600 de  244228
98800 de  244228
99000 de  244228
99200 de  244228
99400 de  244228
99600 de  244228
99800 de  244228
100000 de  244228
100200 de  244228
100400 de  244228
100600 de  244228
100800 de  244228
101000 de  244228
101200 de  244228
101400 de  244228
101600 de  244228
101800 de  244228
102000 de  244228
102200 de  244228
102400 de  244228
102600 de  244228
102800 de  244228
103000 de  244228
103200 de  244228
103400 de  244228
103600 de  244228
103800 de  244228
104000 de  244228
104200 de  244228
104400 de  244228
104600 de  244228
104800 de  244228
105000 de  244228
105200 de  244228
105400 de  244228
105600 de  244228
105800 de  244228
106000 de  244228
106200 de  244228
106400 de  244228
106600 de  244228
106800 de  244228
107000 de  244228
107200 de  244228
107400 de  244228
107600 de  244228
107800 de  244228
108000 de  244228
108200 de  244228
108400 de  244228
108600 de  244228
108800 de  244228
109000 de  244228
109200 de  244228
109400 de  244228
109600 de  244228
109800 de  244228
110000 de  244228
110200 de  244228
110400 de  244228
110600 de  244228
110800 de  244228
111000 de  244228
111200 de  244228
111400 de  244228
111600 de  244228
111800 de  244228
112000 de  244228
112200 de  244228
112400 de  244228
112600 de  244228
112800 de  244228
113000 de  244228
113200 de  244228
113400 de  244228
113600 de  244228
113800 de  244228
114000 de  244228
114200 de  244228
114400 de  244228
114600 de  244228
114800 de  244228
115000 de  244228
115200 de  244228
115400 de  244228
115600 de  244228
115800 de  244228
116000 de  244228
116200 de  244228
116400 de  244228
116600 de  244228
116800 de  244228
117000 de  244228
117200 de  244228
117400 de  244228
117600 de  244228
117800 de  244228
118000 de  244228
118200 de  244228
118400 de  244228
118600 de  244228
118800 de  244228
119000 de  244228
119200 de  244228
119400 de  244228
119600 de  244228
119800 de  244228
120000 de  244228
120200 de  244228
120400 de  244228
120600 de  244228
120800 de  244228
121000 de  244228
121200 de  244228
121400 de  244228
121600 de  244228
121800 de  244228
122000 de  244228
122200 de  244228
122400 de  244228
122600 de  244228
122800 de  244228
123000 de  244228
123200 de  244228
123400 de  244228
123600 de  244228
123800 de  244228
124000 de  244228
124200 de  244228
124400 de  244228
124600 de  244228
124800 de  244228
125000 de  244228
125200 de  244228
125400 de  244228
125600 de  244228
125800 de  244228
126000 de  244228
126200 de  244228
126400 de  244228
126600 de  244228
126800 de  244228
127000 de  244228
127200 de  244228
127400 de  244228
127600 de  244228
127800 de  244228
128000 de  244228
128200 de  244228
128400 de  244228
128600 de  244228
128800 de  244228
129000 de  244228
129200 de  244228
129400 de  244228
129600 de  244228
129800 de  244228
130000 de  244228
130200 de  244228
130400 de  244228
130600 de  244228
130800 de  244228
131000 de  244228
131200 de  244228
131400 de  244228
131600 de  244228
131800 de  244228
132000 de  244228
132200 de  244228
132400 de  244228
132600 de  244228
132800 de  244228
133000 de  244228
133200 de  244228
133400 de  244228
133600 de  244228
133800 de  244228
134000 de  244228
134200 de  244228
134400 de  244228
134600 de  244228
134800 de  244228
135000 de  244228
135200 de  244228
135400 de  244228
135600 de  244228
135800 de  244228
136000 de  244228
136200 de  244228
136400 de  244228
136600 de  244228
136800 de  244228
137000 de  244228
137200 de  244228
137400 de  244228
137600 de  244228
137800 de  244228
138000 de  244228
138200 de  244228
138400 de  244228
138600 de  244228
138800 de  244228
139000 de  244228
139200 de  244228
139400 de  244228
139600 de  244228
139800 de  244228
140000 de  244228
140200 de  244228
140400 de  244228
140600 de  244228
140800 de  244228
141000 de  244228
141200 de  244228
141400 de  244228
141600 de  244228
141800 de  244228
142000 de  244228
142200 de  244228
142400 de  244228
142600 de  244228
142800 de  244228
143000 de  244228
143200 de  244228
143400 de  244228
143600 de  244228
143800 de  244228
144000 de  244228
144200 de  244228
144400 de  244228
144600 de  244228
144800 de  244228
145000 de  244228
145200 de  244228
145400 de  244228
145600 de  244228
145800 de  244228
146000 de  244228
146200 de  244228
146400 de  244228
146600 de  244228
146800 de  244228
147000 de  244228
147200 de  244228
147400 de  244228
147600 de  244228
147800 de  244228
148000 de  244228
148200 de  244228
148400 de  244228
148600 de  244228
148800 de  244228
149000 de  244228
149200 de  244228
149400 de  244228
149600 de  244228
149800 de  244228
150000 de  244228
150200 de  244228
150400 de  244228
150600 de  244228
150800 de  244228
151000 de  244228
151200 de  244228
151400 de  244228
151600 de  244228
151800 de  244228
152000 de  244228
152200 de  244228
152400 de  244228
152600 de  244228
152800 de  244228
153000 de  244228
153200 de  244228
153400 de  244228
153600 de  244228
153800 de  244228
154000 de  244228
154200 de  244228
154400 de  244228
154600 de  244228
154800 de  244228
155000 de  244228
155200 de  244228
155400 de  244228
155600 de  244228
155800 de  244228
156000 de  244228
156200 de  244228
156400 de  244228
156600 de  244228
156800 de  244228
157000 de  244228
157200 de  244228
157400 de  244228
157600 de  244228
157800 de  244228
158000 de  244228
158200 de  244228
158400 de  244228
158600 de  244228
158800 de  244228
159000 de  244228
159200 de  244228
159400 de  244228
159600 de  244228
159800 de  244228
160000 de  244228
160200 de  244228
160400 de  244228
160600 de  244228
160800 de  244228
161000 de  244228
161200 de  244228
161400 de  244228
161600 de  244228
161800 de  244228
162000 de  244228
162200 de  244228
162400 de  244228
162600 de  244228
162800 de  244228
163000 de  244228
163200 de  244228
163400 de  244228
163600 de  244228
163800 de  244228
164000 de  244228
164200 de  244228
164400 de  244228
164600 de  244228
164800 de  244228
165000 de  244228
165200 de  244228
165400 de  244228
165600 de  244228
165800 de  244228
166000 de  244228
166200 de  244228
166400 de  244228
166600 de  244228
166800 de  244228
167000 de  244228
167200 de  244228
167400 de  244228
167600 de  244228
167800 de  244228
168000 de  244228
168200 de  244228
168400 de  244228
168600 de  244228
168800 de  244228
169000 de  244228
169200 de  244228
169400 de  244228
169600 de  244228
169800 de  244228
170000 de  244228
170200 de  244228
170400 de  244228
170600 de  244228
170800 de  244228
171000 de  244228
171200 de  244228
171400 de  244228
171600 de  244228
171800 de  244228
172000 de  244228
172200 de  244228
172400 de  244228
172600 de  244228
172800 de  244228
173000 de  244228
173200 de  244228
173400 de  244228
173600 de  244228
173800 de  244228
174000 de  244228
174200 de  244228
174400 de  244228
174600 de  244228
174800 de  244228
175000 de  244228
175200 de  244228
175400 de  244228
175600 de  244228
175800 de  244228
176000 de  244228
176200 de  244228
176400 de  244228
176600 de  244228
176800 de  244228
177000 de  244228
177200 de  244228
177400 de  244228
177600 de  244228
177800 de  244228
178000 de  244228
178200 de  244228
178400 de  244228
178600 de  244228
178800 de  244228
179000 de  244228
179200 de  244228
179400 de  244228
179600 de  244228
179800 de  244228
180000 de  244228
180200 de  244228
180400 de  244228
180600 de  244228
180800 de  244228
181000 de  244228
181200 de  244228
181400 de  244228
181600 de  244228
181800 de  244228
182000 de  244228
182200 de  244228
182400 de  244228
182600 de  244228
182800 de  244228
183000 de  244228
183200 de  244228
183400 de  244228
183600 de  244228
183800 de  244228
184000 de  244228
184200 de  244228
184400 de  244228
184600 de  244228
184800 de  244228
185000 de  244228
185200 de  244228
185400 de  244228
185600 de  244228
185800 de  244228
186000 de  244228
186200 de  244228
186400 de  244228
186600 de  244228
186800 de  244228
187000 de  244228
187200 de  244228
187400 de  244228
187600 de  244228
187800 de  244228
188000 de  244228
188200 de  244228

188400 de  244228
188600 de  244228
188800 de  244228
189000 de  244228
189200 de  244228
189400 de  244228
189600 de  244228
189800 de  244228
190000 de  244228
190200 de  244228
190400 de  244228
190600 de  244228
190800 de  244228
191000 de  244228
191200 de  244228
191400 de  244228
191600 de  244228
191800 de  244228
192000 de  244228
192200 de  244228
192400 de  244228
192600 de  244228
192800 de  244228
193000 de  244228
193200 de  244228
193400 de  244228
193600 de  244228
193800 de  244228
194000 de  244228
194200 de  244228
194400 de  244228
194600 de  244228
194800 de  244228
195000 de  244228
195200 de  244228
195400 de  244228
195600 de  244228
195800 de  244228
196000 de  244228
196200 de  244228
196400 de  244228
196600 de  244228
196800 de  244228
197000 de  244228
197200 de  244228
197400 de  244228
197600 de  244228
197800 de  244228
198000 de  244228
198200 de  244228
198400 de  244228
198600 de  244228
198800 de  244228
199000 de  244228
199200 de  244228
199400 de  244228
199600 de  244228
199800 de  244228
200000 de  244228
200200 de  244228
200400 de  244228
200600 de  244228
200800 de  244228
201000 de  244228
201200 de  244228
201400 de  244228
201600 de  244228
201800 de  244228
202000 de  244228
202200 de  244228
202400 de  244228
202600 de  244228
202800 de  244228
203000 de  244228
203200 de  244228
203400 de  244228
203600 de  244228
203800 de  244228
204000 de  244228
204200 de  244228
204400 de  244228
204600 de  244228
204800 de  244228
205000 de  244228
205200 de  244228
205400 de  244228
205600 de  244228
205800 de  244228
206000 de  244228
206200 de  244228
206400 de  244228
206600 de  244228
206800 de  244228
207000 de  244228
207200 de  244228
207400 de  244228
207600 de  244228
207800 de  244228
208000 de  244228
208200 de  244228
208400 de  244228
208600 de  244228
208800 de  244228
209000 de  244228
209200 de  244228
209400 de  244228
209600 de  244228
209800 de  244228
210000 de  244228
210200 de  244228
210400 de  244228
210600 de  244228
210800 de  244228
211000 de  244228
211200 de  244228
211400 de  244228
211600 de  244228
211800 de  244228
212000 de  244228
212200 de  244228
212400 de  244228
212600 de  244228
212800 de  244228
213000 de  244228
213200 de  244228
213400 de  244228
213600 de  244228
213800 de  244228
214000 de  244228
214200 de  244228
214400 de  244228
214600 de  244228
214800 de  244228
215000 de  244228
215200 de  244228
215400 de  244228
215600 de  244228
215800 de  244228
216000 de  244228
216200 de  244228
216400 de  244228
216600 de  244228
216800 de  244228
217000 de  244228
217200 de  244228
217400 de  244228
217600 de  244228
217800 de  244228
218000 de  244228
218200 de  244228
218400 de  244228
218600 de  244228
218800 de  244228
219000 de  244228
219200 de  244228
219400 de  244228
219600 de  244228
219800 de  244228
220000 de  244228
220200 de  244228
220400 de  244228
220600 de  244228
220800 de  244228
221000 de  244228
221200 de  244228
221400 de  244228
221600 de  244228
221800 de  244228
222000 de  244228
222200 de  244228
222400 de  244228
222600 de  244228
222800 de  244228
223000 de  244228
223200 de  244228
223400 de  244228
223600 de  244228
223800 de  244228
224000 de  244228
224200 de  244228
224400 de  244228
224600 de  244228
224800 de  244228
225000 de  244228
225200 de  244228
225400 de  244228
225600 de  244228
225800 de  244228
226000 de  244228
226200 de  244228
226400 de  244228
226600 de  244228
226800 de  244228
227000 de  244228
227200 de  244228
227400 de  244228
227600 de  244228
227800 de  244228
228000 de  244228
228200 de  244228
228400 de  244228
228600 de  244228
228800 de  244228
229000 de  244228
229200 de  244228
229400 de  244228
229600 de  244228
229800 de  244228
230000 de  244228
230200 de  244228
230400 de  244228
230600 de  244228
230800 de  244228
231000 de  244228
231200 de  244228
231400 de  244228
231600 de  244228
231800 de  244228
232000 de  244228
232200 de  244228
232400 de  244228
232600 de  244228
232800 de  244228
233000 de  244228
233200 de  244228
233400 de  244228
233600 de  244228
233800 de  244228
234000 de  244228
234200 de  244228
234400 de  244228
234600 de  244228
234800 de  244228
235000 de  244228
235200 de  244228
235400 de  244228
235600 de  244228
235800 de  244228
236000 de  244228
236200 de  244228
236400 de  244228
236600 de  244228
236800 de  244228
237000 de  244228
237200 de  244228
237400 de  244228
237600 de  244228
237800 de  244228
238000 de  244228
238200 de  244228
238400 de  244228
238600 de  244228
238800 de  244228
239000 de  244228
239200 de  244228
239400 de  244228
239600 de  244228
239800 de  244228
240000 de  244228
240200 de  244228
240400 de  244228
240600 de  244228
240800 de  244228
241000 de  244228
241200 de  244228
241400 de  244228
241600 de  244228
241800 de  244228
242000 de  244228
242200 de  244228
242400 de  244228
242600 de  244228
242800 de  244228
243000 de  244228
243200 de  244228
243400 de  244228
243600 de  244228
243800 de  244228
244000 de  244228
244200 de  244228

In [102]:
#df_pivot_time['timestamp'] = timestamps

In [103]:
#df_final_time = pd.pivot_table(df_pivot_time, index=['Llaves', 'cluster'], values=['Dewey', 'Peso del prestamos', 'timestamp'], aggfunc={'Dewey': 'first', 'Peso del prestamos': np.mean, 'timestamp': np.mean}).reset_index()

In [104]:
#df_final_time.to_json('./pesos_con_cluster_final_timestamps.json')

In [106]:
df_pesos_clusters_timestamps = pd.read_json('./pesos_con_cluster_final_timestamps.json')
(df_pesos_clusters_timestamps)

        Llaves  cluster      Dewey  Peso del prestamos  timestamp
0       199645       53        900               0.500 2020-02-24
1       199645      143        900               0.500 2020-02-24
2       199810      130       Mapa               0.250 2019-09-18
3       199825      130       Mapa               0.250 2019-09-18
4       200299       14  Partitura               0.125 2018-01-24
...        ...      ...        ...                 ...        ...
185895  937943        9        300               0.250 2019-11-26
185896  938022        0        300               0.250 2019-11-25
185897  938060       25  Partitura               0.250 2019-12-09
185898  938218        9      Video               0.250 2019-12-02
185899  938222        9      Video               0.250 2019-12-02

[185900 rows x 5 columns]